name: InventoryExamplePlugin
version: 1.0.0
main: com.github.eikefab.minecraft.InventoryExamplePlugin
author: eikefab
website: "https://github.com/eikefab/CustomInventory"
commands:
  inventory:
    permission: "inventory.test"
    permission-message: "You don't have permission!"
    aliases: [invsee]
    description: "A command that opens a inventory created by CustomInventory library"